# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 8689fb2846e32bf5eab076f118a5ac63d4b7ad55

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    mail:
        host: smtp.gmail.com
        port: 587
        user: optigrasmtp@gmail.com
        password: optigrasoft
        protocol: smtp
        tls: true
        auth: true
        from: optigrasmtp@gmail.com

    messageSource:
        cacheSeconds: 1

content:
    location: ${user.home}/tmp/kbapp

swagger:
    title: kbapp API
    description: kbapp applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
